  - name: CI - Docker: Build and Push action 
  # You may pin to the exact commit or the version.
  # uses: NRO04/docker-build-push-action@a90e5a1ebe1647c2f47b700a3ec34ddf409c6de4
  uses: NRO04/docker-build-push-action@v2
  with:
    # Name of repository
    name-repository: 
    # Tag for repository
    tag: 
    # Put docker user name here
    docker-username: {{ $secrets.DOCKER_USERNAME }}
    # Password for docker username
    docker-password: {{ $secrets.DOCKER_PASSWORD }}
    # ssh ip
    ssh_host: 160.187.167.92
          
