- name: CI - Docker: Build and Push action
  uses: NRO04/docker-build-push-action@v2
  with:
    # Name of the repository (e.g., username/app-name)
    name-repository: your-dockerhub-username/your-app-name

    # Tag for the image (e.g., latest or from a GitHub variable)
    tag: latest

    # Docker Hub credentials
    docker-username: ${{ secrets.DOCKER_USERNAME }}
    docker-password: ${{ secrets.DOCKER_PASSWORD }}

    # SSH host (optional)
    ssh_host: 160.187.167.92
